# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/aagam-translation:$COMMIT_SHA', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aagam-translation:$COMMIT_SHA']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aagam-translation'
      - '--image'
      - 'gcr.io/$PROJECT_ID/aagam-translation:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY},GOOGLE_CLOUD_PROJECT_PARENT=${_GOOGLE_CLOUD_PROJECT_PARENT}'

images:
  - 'gcr.io/$PROJECT_ID/aagam-translation:$COMMIT_SHA'